# SPDX-License-Identifier: LicenseRef-CSSL-1.0

uicc0 = {
  imsi = "208990100001100";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc = "C42449363BBAD02B66D16BC975D77CC1";
  pdu_sessions = ({ id = 1; dnn = "oai"; nssai_sst = 1; nssai_sd = 0xFFFFFF; });
}

uicc1 = {
  imsi = "208990100001101";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc = "C42449363BBAD02B66D16BC975D77CC1";
  pdu_sessions = ({ id = 1; dnn = "openairinterface"; nssai_sst = 1; nssai_sd = 0x123456; });
}

position0 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
}

position1 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
}

thread-pool = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

RUs = (
  {
    nb_tx = 1;
    nb_rx = 1;
    att_tx = 0;
    att_rx = 0;
    max_rxgain = 110;
    sdr_addrs = "type=b200";
    clock_src = "internal";
    time_src = "internal";
  },
  {
    nb_tx = 1;
    nb_rx = 1;
    att_tx = 0;
    att_rx = 0;
    max_rxgain = 110;
    sdr_addrs = "type=b200";
    clock_src = "internal";
    time_src = "internal";
  }
);

cells = (
  {
    ru_id = 0;
    band = 78;
    rf_freq = 3319680000L;
    rf_offset = 0L;
    numerology = 1;
    N_RB_DL = 106;
    ssb_start = 516;
  },
  {
    ru_id = 1;
    band = 78;
    rf_freq = 3319680000L;
    rf_offset = 0L;
    numerology = 1;
    N_RB_DL = 106;
    ssb_start = 516;
  }
);

rfsimulator = (
  {
    serveraddr = "127.0.0.1";
  },
  {
    serveraddr = "127.0.0.1";
  }
);

channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_1";
  modellist_rfsimu_1 = (
    {
      model_name     = "rfsimu_channel_enB0"
      type           = "AWGN";
      ploss_dB       = 20;
      noise_power_dB = -4;
      forgetfact     = 0;
      offset         = 0;
      ds_tdl         = 0;
    },
    {
      model_name     = "rfsimu_channel_ue0"
      type           = "AWGN";
      ploss_dB       = 20;
      noise_power_dB = -2;
      forgetfact     = 0;
      offset         = 0;
      ds_tdl         = 0;
    }
  );
};
